apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-frontend
  name: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - image: frontend
        name: frontend
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-frontend
  name: demo-frontend-service
spec:
  ports:
  - port: 1377
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-frontend
  type: NodePort